/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiCatalogImagesImageIdRouteImport } from './routes/api/catalog/images.$imageId'
import { Route as ApiReviewsImagesImageIdRouteImport } from './routes/api/reviews/images.$imageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogImagesImageIdRoute = ApiCatalogImagesImageIdRouteImport.update({
  id: '/api/catalog/images/$imageId',
  path: '/api/catalog/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsImagesImageIdRoute = ApiReviewsImagesImageIdRouteImport.update({
  id: '/api/reviews/images/$imageId',
  path: '/api/reviews/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog/images/$imageId': typeof ApiCatalogImagesImageIdRoute
  '/api/reviews/images/$imageId': typeof ApiReviewsImagesImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog/images/$imageId': typeof ApiCatalogImagesImageIdRoute
  '/api/reviews/images/$imageId': typeof ApiReviewsImagesImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog/images/$imageId': typeof ApiCatalogImagesImageIdRoute
  '/api/reviews/images/$imageId': typeof ApiReviewsImagesImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/catalog/images/$imageId'
    | '/api/reviews/images/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/catalog/images/$imageId'
    | '/api/reviews/images/$imageId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/catalog/images/$imageId'
    | '/api/reviews/images/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiCatalogImagesImageIdRoute: typeof ApiCatalogImagesImageIdRoute
  ApiReviewsImagesImageIdRoute: typeof ApiReviewsImagesImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/images/$imageId': {
      id: '/api/catalog/images/$imageId'
      path: '/api/catalog/images/$imageId'
      fullPath: '/api/catalog/images/$imageId'
      preLoaderRoute: typeof ApiCatalogImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/images/$imageId': {
      id: '/api/reviews/images/$imageId'
      path: '/api/reviews/images/$imageId'
      fullPath: '/api/reviews/images/$imageId'
      preLoaderRoute: typeof ApiReviewsImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiCatalogImagesImageIdRoute: ApiCatalogImagesImageIdRoute,
  ApiReviewsImagesImageIdRoute: ApiReviewsImagesImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
